name: Create Commit

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "Sowju"

      - name: Check out with PAT & Commit
        env:
          ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.ACTIONS_TOKEN }}@github.com/sowjumn/go_pro.git
          git fetch origin
          echo "Update on $(date)" >> update.txt
          git add .
          git commit -m "Automated commit at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
          git push origin master
